config/routes.rb
Rails.application.routes.draw do
  
  resources :formulas

  resources :dry_hoppings

  resources :ingredients

  resources :bottlings

  resources :secondary_fermentations

  resources :primary_fermentation_days

  resources :primary_fermentations

  resources :fermentations

  resources :brewing_hops

  resources :brewings

  resources :sweetenings

  resources :filtrations

  resources :mashin_breaks

  resources :mashins

  resources :notes

  resources :styles

  resources :notebooks

  
  get 'users' => "users#index", :as => :users_index

  get 'users/show/:id' => "users#show", :as => :user
  
  get 'users/follow/:id' => "users#follow", :as => :user_follow
  
  get 'users/unfollow/:id' => "users#unfollow", :as => :user_unfollow
  

  get 'home/index'
  
  get "/ingredients/new/:id" => "ingredients#new", :as => :new_ingredient_with_param
   
  get "/notes/new/:id" => "notes#new", :as => :new_note_with_param
  
  get "/mashins/new/:id" => "mashins#new", :as => :new_mashin_with_param
   
  get "/mashin_breaks/new/:id" => "mashin_breaks#new", :as => :new_mashin_break_with_param
  
  get "/filtrations/new/:id" => "filtrations#new", :as => :new_filtration_with_param
  
  get "/sweetenings/new/:id" => "sweetenings#new", :as => :new_sweetening_with_param
  
  get "/brewings/new/:id" => "brewings#new", :as => :new_brewing_with_param
  
  get "/brewing_hops/new/:id" => "brewing_hops#new", :as => :new_brewing_hop_with_param
  
  get "/fermentations/new/:id" => "fermentations#new", :as => :new_fermentation_with_param
  
  get "/primary_fermentations/new/:id" => "primary_fermentations#new", :as => :new_primary_fermentation_with_param
  
  get "/primary_fermentation_days/new/:id" => "primary_fermentation_days#new", :as => :new_primary_fermentation_day_with_param
  
  get "/secondary_fermentations/new/:id" => "secondary_fermentations#new", :as => :new_secondary_fermentation_with_param
  
  get "/dry_hoppings/new/:id" => "dry_hoppings#new", :as => :new_dry_hopping_with_param
  
  get "/bottlings/new/:id" => "bottlings#new", :as => :new_bottling_with_param
  
  get "/formulas/new/:id" => "formulas#new", :as => :new_formula_with_param
  
  get "/formulas/like/:id" => "formulas#like", :as => :formula_like
  
  get "/formulas/unlike/:id" => "formulas#unlike", :as => :formula_unlike
  
  get "/about" => "home#about", :as => :about
  
  
    
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  root to: "feeds#index"
  
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  
  respond_to :html
  
  def index
    if(user_signed_in?)
      users = Follow.where(:follower_id => current_user.id)
      user_ids = users.map(&:followable_id)
      @feeds = Feed.where(:user_id => user_ids).order("created_at DESC")
      @notebooks = current_user.notebooks.order("created_at DESC")
      notebook_ids = @notebooks.map(&:id)
      @formulas = Formula.where(:notebook_id => notebook_ids).order("created_at DESC").limit(3)
      @notebooks = @notebooks[0..2]
      respond_with(@feeds, @notebooks, @formulas)
    else
      respond_to do |format|
        format.html { redirect_to new_user_session_path, notice: "You must be logged in to view this content." }
        format.json { head :no_content }
      end
    end
  end
end

app/views/feeds/index.html.erb
<h1>Dashboard</h1>
<div class="row dashboard">
	<div class="col-md-6 notebooks">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"><i class="fa fa-book"></i> Your recent notebooks</h3>
			</div>
			<div class="panel-body">
				<% if !@notebooks.empty? %>
					<% i = 0 %>
					<% @notebooks.each do |notebook|%>
						<p><strong><%= link_to notebook.name, notebook %> (<%= notebook.bjcp.full_name %>)</strong></p>
						<p>Progress: <%= notebook.progress %>/8, created at: <%= notebook.created_at.strftime('%H:%M, %m.%d.%Y') %></p>
						<% if i < 2 %>
							<hr />
						<% end %>
						<% i = i + 1 %>
					<% end %>
				<% else %>
					<p>You haven't created any notebooks yet. Start brewing with us!</p>
					<p><%= link_to '<i class="fa fa-beer"></i> New notebook'.html_safe, new_notebook_path, :class => 'btn btn-info' %></p>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-6 formulas">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"><i class="fa fa-list-ol"></i> Your recent formulas</h3>
			</div>
			<div class="panel-body">
				<% if !@formulas.empty? %>
					<% i = 0 %>
					<% @formulas.each do |formula|%>
						<p><strong><%= link_to formula.name, formula %> (<%= formula.notebook.bjcp.full_name %>)</strong></p>
						<p>Published at: <%= formula.created_at.strftime('%H:%M, %m.%d.%Y') %></p>
						<% if i < 2 %>
							<hr />
						<% end %>
						<% i = i + 1 %>
					<% end %>
				<% else %>
					<p>You haven't published any formulas yet!</p>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-12 feed-container">
		<div class="panel panel-default panel-feed">
			<div class="panel-heading">
				<h3 class="panel-title"><i class="fa fa-list-ol"></i> News feed</h3>
			</div>
			<div class="panel-body">
				<% if !@feeds.empty? %>
					<% @feeds.each do |feed| %>
					<div class="col-md-12 feed">
							<% resource = feed.reference_type.titleize %>
							<% object = feed.reference_type.singularize.classify.constantize.find(feed.reference_id) %>
							<div class="user-info">
								<%= image_tag feed.user.avatar.url(:thumb) %>
								<strong><%= link_to feed.user.full_name, feed.user %></strong>
								<%= feed.action_desc %>
								<% if object.is_a? User %>
									<strong><a href="<%= url_for(object) %>"><%= object.full_name %> <%= image_tag feed.user.avatar.url(:thumb) %></a></strong>
									<!--strong><%= link_to object.full_name, object %></strong-->
								<% else %>
									<strong><%= link_to object.name, object %></strong>
								<% end %>
								<small>on <%= feed.created_at.strftime('%H:%M, %m.%d.%Y')%></small>
							</div>
					</div>
					<% end %>
				<% else %>
					<p>No recent activity.</p>
					<p><%= link_to '<i class="fa fa-users"></i> Find friends'.html_safe, users_index_path, :class => 'btn btn-info' %></p>
				<% end %>
			</div>
		</div>
	</div>
</div>