config/routes.rb
Rails.application.routes.draw do
  
  resources :formulas

  resources :dry_hoppings

  resources :ingredients

  resources :bottlings

  resources :secondary_fermentations

  resources :primary_fermentation_days

  resources :primary_fermentations

  resources :fermentations

  resources :brewing_hops

  resources :brewings

  resources :sweetenings

  resources :filtrations

  resources :mashin_breaks

  resources :mashins

  resources :notes

  resources :styles

  resources :notebooks

  
  get 'users' => "users#index", :as => :users_index

  get 'users/show/:id' => "users#show", :as => :user
  
  get 'users/follow/:id' => "users#follow", :as => :user_follow
  
  get 'users/unfollow/:id' => "users#unfollow", :as => :user_unfollow
  

  get 'home/index'
  
  get "/ingredients/new/:id" => "ingredients#new", :as => :new_ingredient_with_param
   
  get "/notes/new/:id" => "notes#new", :as => :new_note_with_param
  
  get "/mashins/new/:id" => "mashins#new", :as => :new_mashin_with_param
   
  get "/mashin_breaks/new/:id" => "mashin_breaks#new", :as => :new_mashin_break_with_param
  
  get "/filtrations/new/:id" => "filtrations#new", :as => :new_filtration_with_param
  
  get "/sweetenings/new/:id" => "sweetenings#new", :as => :new_sweetening_with_param
  
  get "/brewings/new/:id" => "brewings#new", :as => :new_brewing_with_param
  
  get "/brewing_hops/new/:id" => "brewing_hops#new", :as => :new_brewing_hop_with_param
  
  get "/fermentations/new/:id" => "fermentations#new", :as => :new_fermentation_with_param
  
  get "/primary_fermentations/new/:id" => "primary_fermentations#new", :as => :new_primary_fermentation_with_param
  
  get "/primary_fermentation_days/new/:id" => "primary_fermentation_days#new", :as => :new_primary_fermentation_day_with_param
  
  get "/secondary_fermentations/new/:id" => "secondary_fermentations#new", :as => :new_secondary_fermentation_with_param
  
  get "/dry_hoppings/new/:id" => "dry_hoppings#new", :as => :new_dry_hopping_with_param
  
  get "/bottlings/new/:id" => "bottlings#new", :as => :new_bottling_with_param
  
  get "/formulas/new/:id" => "formulas#new", :as => :new_formula_with_param
  
  get "/formulas/like/:id" => "formulas#like", :as => :formula_like
  
  get "/formulas/unlike/:id" => "formulas#unlike", :as => :formula_unlike
  
  get "/about" => "home#about", :as => :about
  
  
    
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  root to: "feeds#index"
  
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :notebooks
  
  validates :name, presence: true
  validates :description, presence: true
  validates :abv, presence: true
  
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @styles = Style.all
    respond_with(@styles)
  end

  def show
    respond_with(@style)
  end

  def new
    if(user_signed_in?)
      @style = Style.new
      respond_with(@style)
    else
      respond_to do |format|
        format.html { redirect_to new_user_session_path, notice: "You must be logged in to view this content." }
        format.json { head :no_content }
      end
    end
  end

  def edit
  end

  def create
    @style = Style.new(style_params)
    @style.save
    respond_with(@style)
  end

  def update
    @style.update(style_params)
    respond_with(@style)
  end

  def destroy
    @style.destroy
    respond_with(@style)
  end

  private
    def set_style
      @style = Style.find(params[:id])
    end

    def style_params
      params.require(:style).permit(:name, :description, :abv)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_area :abv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Abv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.name %></td>
        <td><%= style.description %></td>
        <td><%= style.abv %></td>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @style.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @style.description %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @style.abv %>
</p>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>